2023-03-22 11:17:31,499 INFO    MainThread:8940 [wandb_setup.py:_flush():76] Configure stats pid to 8940
2023-03-22 11:17:31,500 INFO    MainThread:8940 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Administrator\.config\wandb\settings
2023-03-22 11:17:31,500 INFO    MainThread:8940 [wandb_setup.py:_flush():76] Loading settings from D:\d2l-zh\pytorch\object_detection\yolov5-7.0-SeaDronesSee\wandb\settings
2023-03-22 11:17:31,500 INFO    MainThread:8940 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-22 11:17:31,500 INFO    MainThread:8940 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'd:\\d2l-zh\\pytorch\\object_detection\\yolov5-7.0-SeaDronesSee\\train.py'}
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_setup.py:_flush():76] Applying login settings: {'login_timeout': 30}
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_init.py:_log_setup():506] Logging user logs to D:\d2l-zh\pytorch\object_detection\yolov5-7.0-SeaDronesSee\wandb\run-20230322_111731-6klqltfd\logs\debug.log
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_init.py:_log_setup():507] Logging internal logs to D:\d2l-zh\pytorch\object_detection\yolov5-7.0-SeaDronesSee\wandb\run-20230322_111731-6klqltfd\logs\debug-internal.log
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_init.py:init():546] calling init triggers
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {}
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_init.py:init():602] starting backend
2023-03-22 11:17:31,504 INFO    MainThread:8940 [wandb_init.py:init():606] setting up manager
2023-03-22 11:17:31,508 INFO    MainThread:8940 [wandb_init.py:init():613] backend started and connected
2023-03-22 11:17:31,510 INFO    MainThread:8940 [wandb_init.py:init():701] updated telemetry
2023-03-22 11:17:31,511 INFO    MainThread:8940 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-22 11:18:13,874 WARNING MainThread:8940 [wandb_init.py:init():1165] interrupted
Traceback (most recent call last):
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\wandb_init.py", line 1144, in init
    run = wi.init()
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\wandb_init.py", line 744, in init
    result = run_init_handle.wait(
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "D:\Anaconda3\envs\d2l\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "D:\Anaconda3\envs\d2l\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "D:\Anaconda3\envs\d2l\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-03-22 12:29:38,989 WARNING MsgRouterThr:8940 [router.py:message_loop():77] message_loop has been closed
